In [1]:
import numpy as np

In [3]:
arr=np.arange(10,20,3)
print(arr)

[10 13 16 19]


In [7]:
arr1=np.zeros(10)
print(arr1)
arr2=np.ones(10)
print(arr2)
print(arr2 * 5)
print(arr2 * 10)
print(arr2 * 20)
print(arr2 * 50)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]


In [11]:
arr_1=np.arange(30,71,1)
print(arr_1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [12]:
arr_2=np.arange(50,96,1)
print(arr_2)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [6]:
arr_3=np.arange(20,81,2)
print(arr_3)

NameError: name 'np' is not defined

In [7]:
arr_4 =np.arange(21,80,2)
print(arr_4)

NameError: name 'np' is not defined

In [18]:
arr5 = np.random.randint(10,40,15)
print(arr5)

[30 22 29 20 29 23 36 17 28 28 33 37 21 35 30]


In [19]:
arr6 = np.random.randint(30,50,10)
print(arr6)

[42 46 33 43 39 30 42 42 42 34]


In [20]:
arr7 = np.random.randint(50,90,20)
print(arr7)

[50 61 60 86 64 81 67 70 53 80 70 63 82 77 87 68 69 83 79 71]
